apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: user-registration
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 686827201478.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: NOTIFICATION_SERVICE_URL
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DEBUG
        livenessProbe:
          httpGet:
            path: /api/users/list/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/users/list/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
