apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: user-registration
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest  # Cambiar por tu imagen ECR luego
        ports:
        - containerPort: 5000
        env:
        - name: SMTP_SERVER
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: SMTP_SERVER
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: SMTP_PORT
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: PORT
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: SMTP_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
